bluetoothLE.startScanning(
  function(){
    console.log('success');
  },
  function(){
    console.log('failure');
  },
  ''
)

bluetoothLE.numberOfDiscoveredPeripherals(
  function(number){
    console.log(number);
  },
  function(){
    console.log('failure');
  },
  ''
)

bluetoothLE.requestConnectedPeripherals(
  function(){
    console.log('success');
  },
  function(){
    console.log('failure');
  },
  ''
)

bluetoothLE.fetchPeripheral(
  function(peripheral){
    console.log(peripheral);
  },
  function(){
    console.log('failure');
  },
  '0'
)